[package]
name = "xxdynamics"
description = "I really don't like xppaut."
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
polars = { version = "0.46.0" }
rayon = "1.10.0"
